[book]
title = "Dogecoin Core [DOGE, Ð]"
description = "Dogecoin CORE Documentation"
authors = ["qlpqlp"]
language = "en"
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/qlpqlp/dogecoin-core-docs/tree/main/"
edit-url-template = "https://github.com/qlpqlp/dogecoin-core-docs/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2